controller_list:
  - name: fake_ur5_ee_controller
    type: $(arg execution_type)
    joints:
      - joint_r
  - name: fake_ur5_arm_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_ur5_arm_ee_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
  - group: ur5_ee
    pose: home
  - group: ur5_arm
    pose: home