ur5_joint_state_controller: # controller to publish joint state
    type: joint_state_controller/JointStateController
    publish_rate: 100

ur5_joint_position_pd_gravity_controller:

    type: ur5_controllers/JointPositionPDGravityController
    state_publish_rate: 100

    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

ur5_joint_position_controller:

    type: ur5_controllers/JointPositionController

    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

    home: [1.57, -1.57, 1.57, 1.57, 1.57, 0]

    kd: [200, 200, 200, 200, 200, 200]
    kp: [800, 800, 800, 800, 800, 800]