ur5_joint_state_controller:

    type: joint_state_controller/JointStateController
    publish_rate: 100

ur5_joint_position_pd_gravity_controller:

    type: ur5_controllers/JointPositionPDGravityController
    state_publish_rate: 100

    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

ur5_joint_position_controller:

    type: ur5_controllers/JointPositionController
    state_publish_rate: 100

    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

ur5_cartesian_pose_controller:

    type: ur5_controllers/CartesianPoseController
    state_publish_rate: 100

    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6